version: '3'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: click2book-fe
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
